# Claude Code Desktop Notifications - One-Line Installer
# irm https://raw.githubusercontent.com/<YOUR_USERNAME>/windows-desktop-notifications/main/install.ps1 | iex

Write-Host '=== Claude Code Desktop Notifications ===' -ForegroundColor Cyan

$ClaudeDir = "$env:USERPROFILE\.claude"
$NotifyPath = "$ClaudeDir\notify.ps1"
$ConfigPath = "$ClaudeDir\notify-config.json"
$SettingsPath = "$ClaudeDir\settings.json"

# 0. Create notify-config.json if not exists
Write-Host '[0/4] Creating notify-config.json...' -ForegroundColor Yellow
if (-not (Test-Path $ConfigPath)) {
    @{ soundDir = "C:\Windows\Media\" } | ConvertTo-Json | Set-Content $ConfigPath -Encoding UTF8
    Write-Host '  -> ' $ConfigPath -ForegroundColor Green
} else {
    Write-Host '  -> already exists, skipping' -ForegroundColor Gray
}

# 1. Deploy notify.ps1
Write-Host '[1/4] Deploying notify.ps1...' -ForegroundColor Yellow
$b64 = "cGFyYW0oCiAgICBbc3RyaW5nXSAkVGl0bGUgPSAiQ2xhdWRlIENvZGUiLAogICAgW3N0cmluZ10gJE1lc3NhZ2UgPSAiTm90aWZpY2F0aW9uIiwKICAgIFtzdHJpbmddICRTb3VuZEZpbGUgPSAiIiwKICAgIFtzd2l0Y2hdICRTaWxlbnQKKQoKQWRkLVR5cGUgLUFzc2VtYmx5TmFtZSBTeXN0ZW0uV2luZG93cy5Gb3JtcwpBZGQtVHlwZSAtQXNzZW1ibHlOYW1lIFN5c3RlbS5EcmF3aW5nCgokY29uZmlnUGF0aCA9ICIkZW52OlVTRVJQUk9GSUxFXC5jbGF1ZGVcbm90aWZ5LWNvbmZpZy5qc29uIgokc291bmREaXIgPSAiQzpcV2luZG93c1xNZWRpYVwiCmlmIChUZXN0LVBhdGggJGNvbmZpZ1BhdGgpIHsKICAgICRjb25maWcgPSBHZXQtQ29udGVudCAkY29uZmlnUGF0aCAtUmF3IHwgQ29udmVydEZyb20tSnNvbgogICAgaWYgKCRjb25maWcuc291bmREaXIgLWFuZCAoVGVzdC1QYXRoICRjb25maWcuc291bmREaXIpKSB7CiAgICAgICAgJHNvdW5kRGlyID0gJGNvbmZpZy5zb3VuZERpcgogICAgfQp9CgppZiAoLW5vdCAkU2lsZW50IC1hbmQgJFNvdW5kRmlsZSAtbmUgIiIpIHsKICAgIGlmIChUZXN0LVBhdGggJFNvdW5kRmlsZSkgewogICAgICAgIChOZXctT2JqZWN0IFN5c3RlbS5NZWRpYS5Tb3VuZFBsYXllciAkU291bmRGaWxlKS5QbGF5KCkKICAgIH0gZWxzZSB7CiAgICAgICAgJHNwID0gSm9pbi1QYXRoICRzb3VuZERpciAkU291bmRGaWxlCiAgICAgICAgaWYgKFRlc3QtUGF0aCAkc3ApIHsgKE5ldy1PYmplY3QgU3lzdGVtLk1lZGlhLlNvdW5kUGxheWVyICRzcCkuUGxheSgpIH0KICAgIH0KfQoKQWRkLVR5cGUgQCIKdXNpbmcgU3lzdGVtOwp1c2luZyBTeXN0ZW0uRHJhd2luZzsKdXNpbmcgU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzOwoKcHVibGljIGNsYXNzIFNpbGVudE5vdGlmaWVyIDogSURpc3Bvc2FibGUKewogICAgcHJpdmF0ZSBjb25zdCBpbnQgTklNX0FERCA9IDA7CiAgICBwcml2YXRlIGNvbnN0IGludCBOSU1fTU9ESUZZID0gMTsKICAgIHByaXZhdGUgY29uc3QgaW50IE5JTV9ERUxFVEUgPSAyOwogICAgcHJpdmF0ZSBjb25zdCBpbnQgTklGX01FU1NBR0UgPSAxOwogICAgcHJpdmF0ZSBjb25zdCBpbnQgTklGX0lDT04gPSAyOwogICAgcHJpdmF0ZSBjb25zdCBpbnQgTklGX0lORk8gPSAweDEwOwogICAgcHJpdmF0ZSBjb25zdCBpbnQgTklJRl9OT05FID0gMDsKICAgIHByaXZhdGUgY29uc3QgaW50IE5JSUZfTk9TT1VORCA9IDB4MTA7CiAgICBwcml2YXRlIGNvbnN0IGludCBXTV9ERVNUUk9ZID0gMHgwMDAyOwogICAgcHJpdmF0ZSBjb25zdCB1aW50IFBNX1JFTU9WRSA9IDE7CgogICAgW0RsbEltcG9ydCgic2hlbGwzMi5kbGwiLCBDaGFyU2V0ID0gQ2hhclNldC5BdXRvKV0KICAgIHByaXZhdGUgc3RhdGljIGV4dGVybiBib29sIFNoZWxsX05vdGlmeUljb24oaW50IGR3TWVzc2FnZSwgcmVmIE5PVElGWUlDT05EQVRBIGxwRGF0YSk7CgogICAgW0RsbEltcG9ydCgidXNlcjMyLmRsbCIpXQogICAgcHJpdmF0ZSBzdGF0aWMgZXh0ZXJuIEludFB0ciBDcmVhdGVXaW5kb3dFeChpbnQgZHdFeFN0eWxlLCBzdHJpbmcgbHBDbGFzc05hbWUsCiAgICAgICAgc3RyaW5nIGxwV2luZG93TmFtZSwgaW50IGR3U3R5bGUsIGludCB4LCBpbnQgeSwgaW50IG5XaWR0aCwgaW50IG5IZWlnaHQsCiAgICAgICAgSW50UHRyIGhXbmRQYXJlbnQsIEludFB0ciBoTWVudSwgSW50UHRyIGhJbnN0YW5jZSwgSW50UHRyIGxwUGFyYW0pOwoKICAgIFtEbGxJbXBvcnQoInVzZXIzMi5kbGwiKV0KICAgIHByaXZhdGUgc3RhdGljIGV4dGVybiBib29sIERlc3Ryb3lXaW5kb3coSW50UHRyIGhXbmQpOwoKICAgIFtEbGxJbXBvcnQoInVzZXIzMi5kbGwiKV0KICAgIHByaXZhdGUgc3RhdGljIGV4dGVybiBib29sIFBlZWtNZXNzYWdlKG91dCBNU0cgbHBNc2csIEludFB0ciBoV25kLCB1aW50IHdNc2dGaWx0ZXJNaW4sIHVpbnQgd01zZ0ZpbHRlck1heCwgdWludCB3UmVtb3ZlTXNnKTsKCiAgICBbRGxsSW1wb3J0KCJ1c2VyMzIuZGxsIildCiAgICBwcml2YXRlIHN0YXRpYyBleHRlcm4gYm9vbCBUcmFuc2xhdGVNZXNzYWdlKHJlZiBNU0cgbHBNc2cpOwoKICAgIFtEbGxJbXBvcnQoInVzZXIzMi5kbGwiKV0KICAgIHByaXZhdGUgc3RhdGljIGV4dGVybiBJbnRQdHIgRGlzcGF0Y2hNZXNzYWdlKHJlZiBNU0cgbHBNc2cpOwoKICAgIFtEbGxJbXBvcnQoImtlcm5lbDMyLmRsbCIpXQogICAgcHJpdmF0ZSBzdGF0aWMgZXh0ZXJuIEludFB0ciBHZXRNb2R1bGVIYW5kbGUoc3RyaW5nIGxwTW9kdWxlTmFtZSk7CgogICAgW0RsbEltcG9ydCgidXNlcjMyLmRsbCIpXQogICAgcHJpdmF0ZSBzdGF0aWMgZXh0ZXJuIHVzaG9ydCBSZWdpc3RlckNsYXNzKHJlZiBXTkRDTEFTUyBscFduZENsYXNzKTsKCiAgICBbU3RydWN0TGF5b3V0KExheW91dEtpbmQuU2VxdWVudGlhbCwgQ2hhclNldCA9IENoYXJTZXQuQXV0byldCiAgICBwcml2YXRlIHN0cnVjdCBOT1RJRllJQ09OREFUQQogICAgewogICAgICAgIHB1YmxpYyBpbnQgY2JTaXplOwogICAgICAgIHB1YmxpYyBJbnRQdHIgaFduZDsKICAgICAgICBwdWJsaWMgdWludCB1SUQ7CiAgICAgICAgcHVibGljIHVpbnQgdUZsYWdzOwogICAgICAgIHB1YmxpYyB1aW50IHVDYWxsYmFja01lc3NhZ2U7CiAgICAgICAgcHVibGljIEludFB0ciBoSWNvbjsKICAgICAgICBbTWFyc2hhbEFzKFVubWFuYWdlZFR5cGUuQnlWYWxUU3RyLCBTaXplQ29uc3QgPSAxMjgpXSBwdWJsaWMgc3RyaW5nIHN6VGlwOwogICAgICAgIHB1YmxpYyB1aW50IGR3U3RhdGU7CiAgICAgICAgcHVibGljIHVpbnQgZHdTdGF0ZU1hc2s7CiAgICAgICAgW01hcnNoYWxBcyhVbm1hbmFnZWRUeXBlLkJ5VmFsVFN0ciwgU2l6ZUNvbnN0ID0gMjU2KV0gcHVibGljIHN0cmluZyBzekluZm87CiAgICAgICAgcHVibGljIHVpbnQgdVRpbWVvdXRPclZlcnNpb247CiAgICAgICAgW01hcnNoYWxBcyhVbm1hbmFnZWRUeXBlLkJ5VmFsVFN0ciwgU2l6ZUNvbnN0ID0gNjQpXSBwdWJsaWMgc3RyaW5nIHN6SW5mb1RpdGxlOwogICAgICAgIHB1YmxpYyB1aW50IGR3SW5mb0ZsYWdzOwogICAgfQoKICAgIFtTdHJ1Y3RMYXlvdXQoTGF5b3V0S2luZC5TZXF1ZW50aWFsKV0KICAgIHByaXZhdGUgc3RydWN0IE1TRyB7IHB1YmxpYyBJbnRQdHIgaHduZDsgcHVibGljIHVpbnQgbWVzc2FnZTsgcHVibGljIEludFB0ciB3UGFyYW07IHB1YmxpYyBJbnRQdHIgbFBhcmFtOyBwdWJsaWMgdWludCB0aW1lOyBwdWJsaWMgaW50IHB0X3g7IHB1YmxpYyBpbnQgcHRfeTsgfQoKICAgIFtTdHJ1Y3RMYXlvdXQoTGF5b3V0S2luZC5TZXF1ZW50aWFsKV0KICAgIHByaXZhdGUgc3RydWN0IFdORENMQVNTIHsgcHVibGljIHVpbnQgc3R5bGU7IHB1YmxpYyBJbnRQdHIgbHBmblduZFByb2M7IHB1YmxpYyBpbnQgY2JDbHNFeHRyYTsgcHVibGljIGludCBjYlduZEV4dHJhOyBwdWJsaWMgSW50UHRyIGhJbnN0YW5jZTsgcHVibGljIEludFB0ciBoSWNvbjsgcHVibGljIEludFB0ciBoQ3Vyc29yOyBwdWJsaWMgSW50UHRyIGhickJhY2tncm91bmQ7IHB1YmxpYyBzdHJpbmcgbHBzek1lbnVOYW1lOyBwdWJsaWMgc3RyaW5nIGxwc3pDbGFzc05hbWU7IH0KCiAgICBwcml2YXRlIEludFB0ciBoV25kOwogICAgcHJpdmF0ZSBOT1RJRllJQ09OREFUQSBuaWQ7CiAgICBwcml2YXRlIGJvb2wgc2hvd247CgogICAgcHJpdmF0ZSBzdGF0aWMgSW50UHRyIFduZFByb2MoSW50UHRyIGhXbmQsIHVpbnQgbXNnLCBJbnRQdHIgd1BhcmFtLCBJbnRQdHIgbFBhcmFtKQogICAgewogICAgICAgIHJldHVybiBEZWZXaW5kb3dQcm9jVyhoV25kLCBtc2csIHdQYXJhbSwgbFBhcmFtKTsKICAgIH0KCiAgICBbRGxsSW1wb3J0KCJ1c2VyMzIuZGxsIildCiAgICBwcml2YXRlIHN0YXRpYyBleHRlcm4gSW50UHRyIERlZldpbmRvd1Byb2NXKEludFB0ciBoV25kLCB1aW50IG1zZywgSW50UHRyIHdQYXJhbSwgSW50UHRyIGxQYXJhbSk7CgogICAgcHVibGljIHZvaWQgU2hvdyhzdHJpbmcgdGl0bGUsIHN0cmluZyBtZXNzYWdlLCBpbnQgdGltZW91dE1zKQogICAgewogICAgICAgIHN0cmluZyBjbiA9ICJTTl8iICsgR3VpZC5OZXdHdWlkKCkuVG9TdHJpbmcoIk4iKTsKICAgICAgICBXTkRDTEFTUyB3Yzsgd2Muc3R5bGUgPSAwOyB3Yy5jYkNsc0V4dHJhID0gMDsgd2MuY2JXbmRFeHRyYSA9IDA7CiAgICAgICAgd2MubHBmblduZFByb2MgPSBNYXJzaGFsLkdldEZ1bmN0aW9uUG9pbnRlckZvckRlbGVnYXRlKChXbmRQcm9jRGVsZWdhdGUpV25kUHJvYyk7CiAgICAgICAgd2MuaEluc3RhbmNlID0gR2V0TW9kdWxlSGFuZGxlKG51bGwpOyB3Yy5scHN6Q2xhc3NOYW1lID0gY247CiAgICAgICAgd2MuaEljb24gPSBJbnRQdHIuWmVybzsgd2MuaEN1cnNvciA9IEludFB0ci5aZXJvOyB3Yy5oYnJCYWNrZ3JvdW5kID0gSW50UHRyLlplcm87IHdjLmxwc3pNZW51TmFtZSA9IG51bGw7CiAgICAgICAgUmVnaXN0ZXJDbGFzcyhyZWYgd2MpOwogICAgICAgIGhXbmQgPSBDcmVhdGVXaW5kb3dFeCgwLCBjbiwgIiIsIDAsIDAsIDAsIDAsIDAsIEludFB0ci5aZXJvLCBJbnRQdHIuWmVybywgd2MuaEluc3RhbmNlLCBJbnRQdHIuWmVybyk7CgogICAgICAgIHVzaW5nIChJY29uIGljb24gPSBTeXN0ZW1JY29ucy5JbmZvcm1hdGlvbikKICAgICAgICB7CiAgICAgICAgICAgIG5pZC5jYlNpemUgPSBNYXJzaGFsLlNpemVPZih0eXBlb2YoTk9USUZZSUNPTkRBVEEpKTsKICAgICAgICAgICAgbmlkLmhXbmQgPSBoV25kOyBuaWQudUlEID0gMTsKICAgICAgICAgICAgbmlkLnVGbGFncyA9IE5JRl9NRVNTQUdFIHwgTklGX0lDT04gfCBOSUZfSU5GTzsKICAgICAgICAgICAgbmlkLnVDYWxsYmFja01lc3NhZ2UgPSAweDgwMDE7CiAgICAgICAgICAgIG5pZC5oSWNvbiA9IGljb24uSGFuZGxlOwogICAgICAgICAgICBuaWQuc3pUaXAgPSAiIjsKICAgICAgICAgICAgbmlkLnN6SW5mb1RpdGxlID0gdGl0bGU7IG5pZC5zekluZm8gPSBtZXNzYWdlOwogICAgICAgICAgICBuaWQudVRpbWVvdXRPclZlcnNpb24gPSAodWludCl0aW1lb3V0TXM7CiAgICAgICAgICAgIG5pZC5kd0luZm9GbGFncyA9IE5JSUZfTk9ORSB8IE5JSUZfTk9TT1VORDsKICAgICAgICAgICAgU2hlbGxfTm90aWZ5SWNvbihOSU1fQURELCByZWYgbmlkKTsKICAgICAgICB9CiAgICAgICAgc2hvd24gPSB0cnVlOwogICAgfQoKICAgIHB1YmxpYyB2b2lkIFB1bXAoaW50IHRpbWVvdXRNcykKICAgIHsKICAgICAgICBpbnQgZW5kID0gRW52aXJvbm1lbnQuVGlja0NvdW50ICsgdGltZW91dE1zICsgNTAwOwogICAgICAgIE1TRyBtc2c7CiAgICAgICAgd2hpbGUgKEVudmlyb25tZW50LlRpY2tDb3VudCA8IGVuZCkKICAgICAgICB7CiAgICAgICAgICAgIGlmIChQZWVrTWVzc2FnZShvdXQgbXNnLCBJbnRQdHIuWmVybywgMCwgMCwgUE1fUkVNT1ZFKSkKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgVHJhbnNsYXRlTWVzc2FnZShyZWYgbXNnKTsKICAgICAgICAgICAgICAgIERpc3BhdGNoTWVzc2FnZShyZWYgbXNnKTsKICAgICAgICAgICAgfQogICAgICAgICAgICBlbHNlIHsgU3lzdGVtLlRocmVhZGluZy5UaHJlYWQuU2xlZXAoNTApOyB9CiAgICAgICAgfQogICAgfQoKICAgIHByaXZhdGUgZGVsZWdhdGUgSW50UHRyIFduZFByb2NEZWxlZ2F0ZShJbnRQdHIgaFduZCwgdWludCBtc2csIEludFB0ciB3UGFyYW0sIEludFB0ciBsUGFyYW0pOwoKICAgIHB1YmxpYyB2b2lkIERpc3Bvc2UoKQogICAgewogICAgICAgIGlmIChzaG93bikgeyBTaGVsbF9Ob3RpZnlJY29uKE5JTV9ERUxFVEUsIHJlZiBuaWQpOyBzaG93biA9IGZhbHNlOyB9CiAgICAgICAgaWYgKGhXbmQgIT0gSW50UHRyLlplcm8pIHsgRGVzdHJveVdpbmRvdyhoV25kKTsgaFduZCA9IEludFB0ci5aZXJvOyB9CiAgICB9Cn0KIkAgLVJlZmVyZW5jZWRBc3NlbWJsaWVzICJTeXN0ZW0uV2luZG93cy5Gb3JtcyIsIlN5c3RlbS5EcmF3aW5nIgoKJG4gPSBOZXctT2JqZWN0IFNpbGVudE5vdGlmaWVyCnRyeSB7ICRuLlNob3coJFRpdGxlLCAkTWVzc2FnZSwgNTAwMCk7ICRuLlB1bXAoNTAwMCkgfSBmaW5hbGx5IHsgJG4uRGlzcG9zZSgpIH0="
[System.IO.File]::WriteAllText($NotifyPath, [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64)))
Write-Host '  -> ' $NotifyPath -ForegroundColor Green

# 2. Configure hooks
Write-Host '[2/4] Configuring hooks...' -ForegroundColor Yellow
if (Test-Path $SettingsPath) {
    $settings = Get-Content $SettingsPath -Raw | ConvertFrom-Json
} else {
    $settings = @{}
}
if (-not $settings.hooks) {
    $settings | Add-Member -MemberType NoteProperty -Name hooks -Value @{} -Force
}

$permCmd = 'powershell -NoProfile -ExecutionPolicy Bypass -File "' + $NotifyPath + '" -Title "需要确认" -Message "Claude Code 需要你的权限批准" -SoundFile "chimes.wav"'
$stopCmd = 'powershell -NoProfile -ExecutionPolicy Bypass -File "' + $NotifyPath + '" -Title "任务完成" -Message "Claude Code 已完成当前任务" -SoundFile "tada.wav"'

$newPerm = @{matcher=''; hooks=@(@{type='command'; command=$permCmd; timeout=30; async=$true})}
$newStop = @{matcher=''; hooks=@(@{type='command'; command=$stopCmd; timeout=30; async=$true})}

$h = $settings.hooks
if (-not $h.PermissionRequest) { $h | Add-Member -Name PermissionRequest -Value @() -Force }
$h.PermissionRequest += $newPerm
if (-not $h.Stop) { $h | Add-Member -Name Stop -Value @() -Force }
$h.Stop += $newStop

# 3. Save
Write-Host '[3/4] Saving settings...' -ForegroundColor Yellow
$settings | ConvertTo-Json -Depth 10 | Set-Content $SettingsPath -Encoding UTF8
Write-Host '  -> ' $SettingsPath -ForegroundColor Green

# 4. Reminder
Write-Host '[4/4] Done!' -ForegroundColor Cyan
Write-Host ''
Write-Host 'To customize your sound directory, just tell Claude:'
Write-Host '  "我把音频文件放在 D:\my-sounds 了"'
Write-Host ''
Write-Host 'Run /hooks or restart Claude Code.' -ForegroundColor Cyan
